### PR TITLE
Minor typo: Should be 2 spaces!

### PR DESCRIPTION
**Pull request by jaredsburrows**
I figured this was a minor typo in the documentation.

### CODE REVIEW

**Comment by christopherperry** [comment]
LGTM

**Comment by jaredsburrows** [comment]
Dup of https://github.com/android/kotlin-guides/pull/9

**Comment by jaredsburrows** [comment]
Trying to change here as well: https://github.com/JetBrains/kotlin-web-site/pull/928

**Comment by jaredsburrows** [comment]
PR: https://github.com/JetBrains/kotlin-web-site/pull/928#event-1325593694 was closed. Closing this.

**Pull request closed without merging**
