### PR TITLE
High priority indentation fix. 

### PR DESCRIPTION
**Pull request by rharter**
Looks like there was an oversight in the indentation portion, but I've fixed it.

### CODE REVIEW

**Comment by rharter** [comment]
giphy 1

**Comment by mroncka** [comment]
Official Kotlin coding conventions suggest using 4 spaces

**Comment by jaredsburrows** [comment]
@yole closed my PR here: https://github.com/JetBrains/kotlin-web-site/pull/928#event-1325593694.

**Comment by JakeWharton** [comment]
We'll be sticking with 4 because JetBrains is.

**Pull request closed without merging**
